version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.12.1
    commands:
      - echo Installing dependencies...
      - yarn install

  build:
    commands:
      - echo Building the application...
      - yarn build

  post_build:
    commands:
      - echo Packaging the application...
      - zip -r build.zip *
      - echo Build complete

artifacts:
  files:
    - build.zip
  discard-paths: yes
  base-directory: .  # Ensure the base directory is correct for your project

cache:
  paths:
    - 'node_modules/**/*'